### ISSUE TITLE
Add validations method.

### ISSUE THREAD

**Issue by matinTayebiNia** [Hesammousavi/express-router-js#1]

**Comment by matinTayebiNia** [comment]
It is not possible to add another method called 'validations' to this package to write a section to put url validations there.

**Comment by Hesammousavi** [comment]
please give me more explanation about this

**Comment by matinTayebiNia** [comment]
https://roocket.ir/discuss/%D8%B3%DB%8C%D8%B3%D8%AA%D9%85-Routing-%D9%BE%DB%8C%D8%B4%D8%B1%D9%81%D8%AA%D9%87-%D8%AA%D8%B1-%D8%A8%D8%B1%D8%A7%DB%8C-Expressjs

**Comment by Hesammousavi** [comment]
```
Router.post("/foo/bar", indexController.index).middleware(Validation());
```
